// flow-typed signature: 65c4be9aeb47547233c075cd1823ea76
// flow-typed version: <<STUB>>/@exponent/ex-navigation_v^6.1.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@exponent/ex-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@exponent/ex-navigation' {
  declare module.exports: any;
}
