// flow-typed signature: e880d0cbb1fc188da00869e6bac52179
// flow-typed version: <<STUB>>/cpf_cnpj_v^0.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cpf_cnpj'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cpf_cnpj' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cpf_cnpj/build/cnpj' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/build/cnpj.min' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/build/cpf_cnpj' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/build/cpf_cnpj.min' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/build/cpf' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/build/cpf.min' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/Gruntfile' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/lib/cnpj' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/lib/cpf' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/spec/cnpj.spec' {
  declare module.exports: any;
}

declare module 'cpf_cnpj/spec/cpf.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cpf_cnpj/build/cnpj.js' {
  declare module.exports: $Exports<'cpf_cnpj/build/cnpj'>;
}
declare module 'cpf_cnpj/build/cnpj.min.js' {
  declare module.exports: $Exports<'cpf_cnpj/build/cnpj.min'>;
}
declare module 'cpf_cnpj/build/cpf_cnpj.js' {
  declare module.exports: $Exports<'cpf_cnpj/build/cpf_cnpj'>;
}
declare module 'cpf_cnpj/build/cpf_cnpj.min.js' {
  declare module.exports: $Exports<'cpf_cnpj/build/cpf_cnpj.min'>;
}
declare module 'cpf_cnpj/build/cpf.js' {
  declare module.exports: $Exports<'cpf_cnpj/build/cpf'>;
}
declare module 'cpf_cnpj/build/cpf.min.js' {
  declare module.exports: $Exports<'cpf_cnpj/build/cpf.min'>;
}
declare module 'cpf_cnpj/Gruntfile.js' {
  declare module.exports: $Exports<'cpf_cnpj/Gruntfile'>;
}
declare module 'cpf_cnpj/index' {
  declare module.exports: $Exports<'cpf_cnpj'>;
}
declare module 'cpf_cnpj/index.js' {
  declare module.exports: $Exports<'cpf_cnpj'>;
}
declare module 'cpf_cnpj/lib/cnpj.js' {
  declare module.exports: $Exports<'cpf_cnpj/lib/cnpj'>;
}
declare module 'cpf_cnpj/lib/cpf.js' {
  declare module.exports: $Exports<'cpf_cnpj/lib/cpf'>;
}
declare module 'cpf_cnpj/spec/cnpj.spec.js' {
  declare module.exports: $Exports<'cpf_cnpj/spec/cnpj.spec'>;
}
declare module 'cpf_cnpj/spec/cpf.spec.js' {
  declare module.exports: $Exports<'cpf_cnpj/spec/cpf.spec'>;
}
