// flow-typed signature: 3af96b033badb9d496fdcbac3a3a6461
// flow-typed version: <<STUB>>/react-native-ua_v^0.1.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-ua'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-ua' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-ua/android/build/intermediates/exploded-aar/com.urbanairship.android/urbanairship-sdk/8.0.4/res/raw/ua_native_bridge' {
  declare module.exports: any;
}

declare module 'react-native-ua/android/build/intermediates/res/merged/release/raw/ua_native_bridge' {
  declare module.exports: any;
}

declare module 'react-native-ua/android/build/intermediates/res/merged/release/raw/ua_native_bridge' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-ua/android/build/intermediates/exploded-aar/com.urbanairship.android/urbanairship-sdk/8.0.4/res/raw/ua_native_bridge.js' {
  declare module.exports: $Exports<'react-native-ua/android/build/intermediates/exploded-aar/com.urbanairship.android/urbanairship-sdk/8.0.4/res/raw/ua_native_bridge'>;
}
declare module 'react-native-ua/android/build/intermediates/res/merged/release/raw/ua_native_bridge.js' {
  declare module.exports: $Exports<'react-native-ua/android/build/intermediates/res/merged/release/raw/ua_native_bridge'>;
}
declare module 'react-native-ua/android/build/intermediates/res/merged/release/raw/ua_native_bridge.js' {
  declare module.exports: $Exports<'react-native-ua/android/build/intermediates/res/merged/release/raw/ua_native_bridge'>;
}
declare module 'react-native-ua/index' {
  declare module.exports: $Exports<'react-native-ua'>;
}
declare module 'react-native-ua/index.js' {
  declare module.exports: $Exports<'react-native-ua'>;
}
