// flow-typed signature: 6fb11084d8c3877a7a9768a463c11275
// flow-typed version: <<STUB>>/react-native-svg-icon_v^0.4.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-svg-icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-svg-icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-svg-icon/lib/components/SvgIcon' {
  declare module.exports: any;
}

declare module 'react-native-svg-icon/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-svg-icon/src/components/SvgIcon' {
  declare module.exports: any;
}

declare module 'react-native-svg-icon/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-svg-icon/lib/components/SvgIcon.js' {
  declare module.exports: $Exports<'react-native-svg-icon/lib/components/SvgIcon'>;
}
declare module 'react-native-svg-icon/lib/index.js' {
  declare module.exports: $Exports<'react-native-svg-icon/lib/index'>;
}
declare module 'react-native-svg-icon/src/components/SvgIcon.js' {
  declare module.exports: $Exports<'react-native-svg-icon/src/components/SvgIcon'>;
}
declare module 'react-native-svg-icon/src/index.js' {
  declare module.exports: $Exports<'react-native-svg-icon/src/index'>;
}
