// flow-typed signature: 9436a0ddc1f7f62feca8a5db2ea6c216
// flow-typed version: <<STUB>>/react-native-bem_v^0.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-bem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-bem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-bem/lib/helpers/generateChildProps' {
  declare module.exports: any;
}

declare module 'react-native-bem/lib/helpers/kebabCase' {
  declare module.exports: any;
}

declare module 'react-native-bem/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-bem/lib/methods/bem' {
  declare module.exports: any;
}

declare module 'react-native-bem/lib/methods/renderBemChildren' {
  declare module.exports: any;
}

declare module 'react-native-bem/src/helpers/generateChildProps' {
  declare module.exports: any;
}

declare module 'react-native-bem/src/helpers/kebabCase' {
  declare module.exports: any;
}

declare module 'react-native-bem/src/index' {
  declare module.exports: any;
}

declare module 'react-native-bem/src/methods/bem' {
  declare module.exports: any;
}

declare module 'react-native-bem/src/methods/renderBemChildren' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-bem/lib/helpers/generateChildProps.js' {
  declare module.exports: $Exports<'react-native-bem/lib/helpers/generateChildProps'>;
}
declare module 'react-native-bem/lib/helpers/kebabCase.js' {
  declare module.exports: $Exports<'react-native-bem/lib/helpers/kebabCase'>;
}
declare module 'react-native-bem/lib/index.js' {
  declare module.exports: $Exports<'react-native-bem/lib/index'>;
}
declare module 'react-native-bem/lib/methods/bem.js' {
  declare module.exports: $Exports<'react-native-bem/lib/methods/bem'>;
}
declare module 'react-native-bem/lib/methods/renderBemChildren.js' {
  declare module.exports: $Exports<'react-native-bem/lib/methods/renderBemChildren'>;
}
declare module 'react-native-bem/src/helpers/generateChildProps.js' {
  declare module.exports: $Exports<'react-native-bem/src/helpers/generateChildProps'>;
}
declare module 'react-native-bem/src/helpers/kebabCase.js' {
  declare module.exports: $Exports<'react-native-bem/src/helpers/kebabCase'>;
}
declare module 'react-native-bem/src/index.js' {
  declare module.exports: $Exports<'react-native-bem/src/index'>;
}
declare module 'react-native-bem/src/methods/bem.js' {
  declare module.exports: $Exports<'react-native-bem/src/methods/bem'>;
}
declare module 'react-native-bem/src/methods/renderBemChildren.js' {
  declare module.exports: $Exports<'react-native-bem/src/methods/renderBemChildren'>;
}
