// flow-typed signature: 0d9adbfc33c907adcbaee791e9ef451b
// flow-typed version: <<STUB>>/react-test-renderer_v15.3.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-test-renderer/index' {
  declare module.exports: $Exports<'react-test-renderer'>;
}
declare module 'react-test-renderer/index.js' {
  declare module.exports: $Exports<'react-test-renderer'>;
}
