// flow-typed signature: e16f9a906e268530bd7c6fdbf5746f99
// flow-typed version: <<STUB>>/totvslabs-ui-framework_v^1.0.21/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'totvslabs-ui-framework'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'totvslabs-ui-framework' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'totvslabs-ui-framework/admin/rest/admin.rest.directory' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/admin/rest/services/addressCleansing.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/admin/rest/services/auth.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/admin/rest/services/dataModel.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/admin/rest/services/filter.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/admin/rest/services/mdm.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/admin/rest/services/processingThreads.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/admin/rest/services/stop.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/admin/rest/services/tenant.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/admin/rest/services/user.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/rest.directory' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/admin.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/applications.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/auth.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/connectors.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/dashboard.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/dataConsumption.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/dataModel.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/etl.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/gremlin.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/log.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/masterOfMasters.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/mdm.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/push.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/relationship.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/resultPanel.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/saml.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/staging.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/tenant.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/totvssm.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/upload.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/mdm-ui/rest/services/user.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/login_example/login.helper' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/login_example/rest_examples' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/fetch.rest.api' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/rest.api' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/admin.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/applications.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/auth.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/connectors.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/dashboard.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/dataConsumption.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/dataModel.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/etl.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/gremlin.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/log.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/masterOfMasters.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/mdm.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/push.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/relationship.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/resultPanel.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/saml.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/staging.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/tenant.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/totvssm.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/upload.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/react-native/rest/services/user.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/assets.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/fetch.rest.api' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/firebase/firebase.auth.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/firebase/firebase.module' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/firebase/firebase.rest.api' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/firebase/firebase.user.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/http.rest.api' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/login/auto-login.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/login/route-login.service' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/rest.api' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/rest.auth' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/rest/route.auth' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/web-styles/gulp/lint' {
  declare module.exports: any;
}

declare module 'totvslabs-ui-framework/web-styles/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'totvslabs-ui-framework/admin/rest/admin.rest.directory.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/admin.rest.directory'>;
}
declare module 'totvslabs-ui-framework/admin/rest/services/addressCleansing.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/services/addressCleansing.service'>;
}
declare module 'totvslabs-ui-framework/admin/rest/services/auth.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/services/auth.service'>;
}
declare module 'totvslabs-ui-framework/admin/rest/services/dataModel.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/services/dataModel.service'>;
}
declare module 'totvslabs-ui-framework/admin/rest/services/filter.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/services/filter.service'>;
}
declare module 'totvslabs-ui-framework/admin/rest/services/mdm.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/services/mdm.service'>;
}
declare module 'totvslabs-ui-framework/admin/rest/services/processingThreads.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/services/processingThreads.service'>;
}
declare module 'totvslabs-ui-framework/admin/rest/services/stop.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/services/stop.service'>;
}
declare module 'totvslabs-ui-framework/admin/rest/services/tenant.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/services/tenant.service'>;
}
declare module 'totvslabs-ui-framework/admin/rest/services/user.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/admin/rest/services/user.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/rest.directory.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/rest.directory'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/admin.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/admin.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/applications.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/applications.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/auth.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/auth.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/connectors.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/connectors.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/dashboard.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/dashboard.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/dataConsumption.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/dataConsumption.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/dataModel.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/dataModel.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/etl.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/etl.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/gremlin.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/gremlin.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/log.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/log.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/masterOfMasters.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/masterOfMasters.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/mdm.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/mdm.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/push.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/push.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/relationship.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/relationship.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/resultPanel.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/resultPanel.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/saml.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/saml.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/staging.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/staging.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/tenant.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/tenant.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/totvssm.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/totvssm.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/upload.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/upload.service'>;
}
declare module 'totvslabs-ui-framework/mdm-ui/rest/services/user.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/mdm-ui/rest/services/user.service'>;
}
declare module 'totvslabs-ui-framework/react-native/login_example/login.helper.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/login_example/login.helper'>;
}
declare module 'totvslabs-ui-framework/react-native/login_example/rest_examples.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/login_example/rest_examples'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/fetch.rest.api.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/fetch.rest.api'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/rest.api.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/rest.api'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/admin.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/admin.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/applications.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/applications.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/auth.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/auth.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/connectors.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/connectors.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/dashboard.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/dashboard.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/dataConsumption.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/dataConsumption.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/dataModel.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/dataModel.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/etl.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/etl.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/gremlin.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/gremlin.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/log.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/log.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/masterOfMasters.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/masterOfMasters.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/mdm.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/mdm.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/push.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/push.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/relationship.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/relationship.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/resultPanel.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/resultPanel.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/saml.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/saml.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/staging.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/staging.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/tenant.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/tenant.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/totvssm.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/totvssm.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/upload.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/upload.service'>;
}
declare module 'totvslabs-ui-framework/react-native/rest/services/user.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/react-native/rest/services/user.service'>;
}
declare module 'totvslabs-ui-framework/rest/assets.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/assets.service'>;
}
declare module 'totvslabs-ui-framework/rest/fetch.rest.api.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/fetch.rest.api'>;
}
declare module 'totvslabs-ui-framework/rest/firebase/firebase.auth.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/firebase/firebase.auth.service'>;
}
declare module 'totvslabs-ui-framework/rest/firebase/firebase.module.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/firebase/firebase.module'>;
}
declare module 'totvslabs-ui-framework/rest/firebase/firebase.rest.api.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/firebase/firebase.rest.api'>;
}
declare module 'totvslabs-ui-framework/rest/firebase/firebase.user.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/firebase/firebase.user.service'>;
}
declare module 'totvslabs-ui-framework/rest/http.rest.api.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/http.rest.api'>;
}
declare module 'totvslabs-ui-framework/rest/login/auto-login.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/login/auto-login.service'>;
}
declare module 'totvslabs-ui-framework/rest/login/route-login.service.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/login/route-login.service'>;
}
declare module 'totvslabs-ui-framework/rest/rest.api.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/rest.api'>;
}
declare module 'totvslabs-ui-framework/rest/rest.auth.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/rest.auth'>;
}
declare module 'totvslabs-ui-framework/rest/route.auth.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/rest/route.auth'>;
}
declare module 'totvslabs-ui-framework/web-styles/gulp/lint.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/web-styles/gulp/lint'>;
}
declare module 'totvslabs-ui-framework/web-styles/gulpfile.js' {
  declare module.exports: $Exports<'totvslabs-ui-framework/web-styles/gulpfile'>;
}
