/** UI */

export const BOTTOM_SHOW = 'bottom_show';
export const BOTTOM_HIDE = 'bottom_hide';
export const SELECT_MENU = 'SELECT_MENU';
export const TOGGLE_MENU = 'TOGGLE_MENU';

/** Data Model */

export const FETCH_DATA_MODELS_REQUEST = 'FETCH_DATA_MODELS_REQUEST';
export const FETCH_DATA_MODELS_SUCCESS = 'FETCH_DATA_MODELS_SUCCESS';
export const FETCH_DATA_MODELS_FAILURE = 'FETCH_DATA_MODELS_FAILURE';

export const GLOBAL_SEARCH_REQUEST = 'GLOBAL_SEARCH_REQUEST';
export const GLOBAL_SEARCH_SUCCESS = 'GLOBAL_SEARCH_SUCCESS';
export const GLOBAL_SEARCH_FAILURE = 'GLOBAL_SEARCH_FAILURE';

export const SET_GOLDEN_DATA_MODELS = 'SET_GOLDEN_DATA_MODELS';

export const SEARCH_RECORDS_REQUEST = 'SEARCH_RECORDS_REQUEST';
export const SEARCH_RECORDS_SUCCESS = 'SEARCH_RECORDS_SUCCESS';
export const SEARCH_RECORDS_FAILURE = 'SEARCH_RECORDS_FAILURE';

/** Dashboard */

export const FETCH_DASHBOARDS_REQUEST = 'FETCH_DASHBOARDS_REQUEST';
export const FETCH_DASHBOARDS_SUCCESS = 'FETCH_DASHBOARDS_SUCCESS';
export const FETCH_DASHBOARDS_FAILURE = 'FETCH_DASHBOARDS_FAILURE';

/** 360 Record */

export const FETCH_RELATIONSHIPS_REQUEST = 'FETCH_RELATIONSHIPS_REQUEST';
export const FETCH_RELATIONSHIPS_SUCCESS = 'FETCH_RELATIONSHIPS_SUCCESS';
export const FETCH_RELATIONSHIPS_FAILURE = 'FETCH_RELATIONSHIPS_FAILURE';
export const FETCH_GOLDEN_RECORD_REQUEST = 'FETCH_GOLDEN_RECORD_REQUEST';
export const FETCH_GOLDEN_RECORD_SUCCESS = 'FETCH_GOLDEN_RECORD_SUCCESS';
export const FETCH_GOLDEN_RECORD_FAILURE = 'FETCH_GOLDEN_RECORD_FAILURE';
export const FETCH_VERTICALS_REQUEST = 'FETCH_VERTICALS_REQUEST';
export const FETCH_VERTICALS_SUCCESS = 'FETCH_VERTICALS_SUCCESS';
export const FETCH_VERTICALS_FAILURE = 'FETCH_VERTICALS_FAILURE';

